version: "3.9"

services:
  transcribe-reels:
    build: .
    container_name: transcribe-reels
    ports:
      - "8501:8501"
    env_file:
      - .env
    volumes:
      - ./export:/app/export
      - ./reel:/app/reel
      - ./.cache:/app/.cache
    restart: unless-stopped
